version: "3.9"
services:
  kernel:
    build:
      context: IotKernel
    ports:
      - 80:80
      - 8266:8266
    volumes:
      - ./IotKernel:/kernel/IotKernel



  mqtt-listener:
    build:
      context: mqttListener

  mosquitto:
    build:
      context: mosquitto
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    container_name: eclipse-mosquitto
    restart: always
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883


  redis:
    image: redis:alpine

  redis-cli:
    image: redis:alpine
    links:
      - redis
    command: redis-cli -h redis config set notify-keyspace-events KEA

  redis_pubsub:
    build:
      context: redis_pubsub

  pacs:
    build:
      context: Modules/pacs
    depends_on:
      - kernel

